{% set name = "opentelemetry-exporter-otlp" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp-{{ version }}.tar.gz
  sha256: d23df4fc22e0a863db2b2117c5a5780d5fa3bbeb65fdce9848d1f98fc3ace4cd

build:
  number: 101
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-exporter-otlp-proto-grpc ==1.34.0
    - opentelemetry-exporter-otlp-proto-http ==1.34.0

test:
  imports:
    - opentelemetry.exporter.otlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  summary: OpenTelemetry Collector Exporters
  description: |
    This library is provided as a convenience to install all supported OpenTelemetry Collector Exporters.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  doc_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp

extra:
  recipe-maintainers:
    - mariusvniekerk