{% set name = "opentelemetry-exporter-otlp" %}
{% set version = "1.37.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp-{{ version }}.tar.gz
  sha256: f85b1929dd0d750751cc9159376fb05aa88bb7a08b6cdbf84edb0054d93e9f26

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-exporter-otlp-proto-grpc =={{ version }}
    - opentelemetry-exporter-otlp-proto-http =={{ version }}

test:
  source_files:
    - tests
  imports:
    - opentelemetry.exporter.otlp
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  summary: OpenTelemetry Collector Exporters
  description: |
    This library is provided as a convenience to install all supported OpenTelemetry Collector Exporters. 
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  doc_url: https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp/README.rst

extra:
  recipe-maintainers:
    - mariusvniekerk
