{% set name = "opentelemetry-exporter-otlp" %}
{% set version = "1.38.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 2f55acdd475e4136117eff20fbf1b9488b1b0b665ab64407516e1ac06f9c3f9d

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-exporter-otlp-proto-grpc =={{ version }}
    - opentelemetry-exporter-otlp-proto-http =={{ version }}

# Tests disabled:
# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
test:
  imports:
    - opentelemetry.exporter.otlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: OpenTelemetry Collector Exporters
  description: |
    This library is provided as a convenience to install all supported OpenTelemetry Collector Exporters. 
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  doc_url: https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp/README.rst

extra:
  recipe-maintainers:
    - mariusvniekerk
